<a href="https://colab.research.google.com/github/usmartsolution/LinearRegressionLab1/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [16]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [17]:
# Print tensors
print(x)
print(w)
print(b)

tensor(3.)
tensor(4., requires_grad=True)
tensor(5., requires_grad=True)


In [18]:
# Arithmetic operations
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [19]:
# Compute gradients
y.backward()

In [20]:
# Display gradients
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dw: tensor(3.)
dy/db: tensor(1.)


In [22]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [23]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [24]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [25]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.7467, -1.3913,  0.8812],
        [-1.5012, -0.1602, -1.5496]], requires_grad=True)
tensor([-0.6247, -0.4323], requires_grad=True)


In [26]:
# Define the model
def model(x):
    return x @ w.t() + b

In [27]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  -1.4380, -187.3872],
        [   1.2915, -250.3146],
        [ -70.9831, -242.3799],
        [  48.3215, -217.7816],
        [ -20.9798, -227.8661]], grad_fn=<AddBackward0>)


In [28]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [29]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [30]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(57761.9883, grad_fn=<DivBackward0>)


In [31]:
# Compute gradients
loss.backward()

In [32]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.7467, -1.3913,  0.8812],
        [-1.5012, -0.1602, -1.5496]], requires_grad=True)
tensor([[ -6768.9575,  -9418.1328,  -5258.9771],
        [-26667.6855, -28543.2578, -17806.2734]])


In [33]:
# Gradients for bias
print(b)
print(b.grad)

tensor([-0.6247, -0.4323], requires_grad=True)
tensor([ -84.9576, -317.1459])


In [34]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [35]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  -1.4380, -187.3872],
        [   1.2915, -250.3146],
        [ -70.9831, -242.3799],
        [  48.3215, -217.7816],
        [ -20.9798, -227.8661]], grad_fn=<AddBackward0>)


In [36]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(57761.9883, grad_fn=<DivBackward0>)


In [37]:
# Compute gradients
loss.backward()

In [38]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [39]:
print(w)

tensor([[ 0.8144, -1.2971,  0.9338],
        [-1.2346,  0.1253, -1.3715]], requires_grad=True)


In [40]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(39503.4414, grad_fn=<DivBackward0>)


In [41]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [42]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(592.3126, grad_fn=<DivBackward0>)


In [43]:
# Print predictions
preds

tensor([[ 66.0964,  71.0675],
        [ 94.1781,  90.2762],
        [ 77.1065, 155.3770],
        [ 74.1978,  40.7274],
        [ 91.6263,  98.8078]], grad_fn=<AddBackward0>)

In [44]:
# Print targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])